### PR TITLE
Fix video publishing

### LINKED ISSUE #218: Unhandled Rejection (Error): The [LocalVideoTrack #2: b4ea0559-c915-4cd4-b278-cc046adc0c2a] was unpublished
**Describe the bug**
During the video meeting switching on/off video sharing button quickly causes the following error.
`Unhandled Rejection (Error): The [LocalVideoTrack #2: b4ea0559-c915-4cd4-b278-cc046adc0c2a] was unpublished`

Here is the screenshot
Screenshot 2020-05-27 at 6 21 41 PM

P.S. I'm running my code locally.

### PR DESCRIPTION
**Pull request by timmydoza**
**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### JIRA link(s):

- [AHOYAPPS-683](https://issues.corp.twilio.com/browse/AHOYAPPS-683)

### Description

This PR changes the logic of the publishing/unpublishing of the local video track in the following ways:

- The Mute Video button is now throttled so that it can only be clicked once every 200ms. This prevents issues caused by clicking the button excessively fast.
- The useLocalVideoToggle hook only publishes/unpublishes the local video track when it is not already doing so.
- If there is a publishing error, an error modal will be displayed instead of the app crashing. 

Resolves #218 and #233 

This PR can be manually tested by entering a room, and then clicking the Mute Video button as quickly as possible. There will be no errors and the button will work as expected. 

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [x] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [x] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

### CODE REVIEW

File: src/components/Controls/ToggleVideoButton/ToggleVideoButton.tsx [hunk 1]
```diff
@@ -19,14 +19,22 @@ const useStyles = makeStyles((theme: Theme) =>
 export default function ToggleVideoButton(props: { disabled?: boolean }) {
   const classes = useStyles();
   const [isVideoEnabled, toggleVideoEnabled] = useLocalVideoToggle();
+  const lastClickTimeRef = useRef(0);
+
+  const toggleVideo = useCallback(() => {
+    if (Date.now() - lastClickTimeRef.current > 200) {
```
Comment (charliesantos) [inline src/components/Controls/ToggleVideoButton/ToggleVideoButton.tsx:25]: I think we should use `lodash.throttle`. Same way how you did it here https://github.com/twilio/twilio-video-app-react/blob/master/src/components/Controls/useIsUserActive/useIsUserActive.ts

Comment (timmydoza) [reply src/components/Controls/ToggleVideoButton/ToggleVideoButton.tsx:25]: It isn't really possible to use `throttle` in this instance. For example, this doesn't work:

```
export default function ToggleVideoButton(props: { disabled?: boolean }) {
  const classes = useStyles();
  const [isVideoEnabled, toggleVideoEnabled] = useLocalVideoToggle();

  const toggleVideo = useCallback(throttle(toggleVideoEnabled, 200), [toggleVideoEnabled]);

  return (
    <Tooltip
      title={isVideoEnabled ? 'Mute Video' : 'Unmute Video'}
      placement="top"
      PopperProps={{ disablePortal: true }}
    >
      <Fab className={classes.fab} onClick={toggleVideo} disabled={props.disabled}>
        {isVideoEnabled ? <Videocam /> : <VideocamOff />}
      </Fab>
    </Tooltip>
  );
}
```

That's because calling `toggleVideoEnabled` will cause `useCallback` to produce a new function (because the `useLocalVideoToggle` creates new `isVideoEnabled` and `toggleVideoEnabled` variables whenever the local video is toggled). So `throttle` ends up being called everytime the button is clicked, which means that the throttle effect is lost because `onClick` calls a new function each time instead of the same function as before.

The example you provided works fine because `useEffect` runs only once (note the empty dependency array). There are some `useThrottle` packages that can be installed from NPM, but I found it easy enough just to do it myself. If we need to add this functionality to other components, then I'll can add my own `useThrottle` hook to the codebase.

Comment (charliesantos) [reply src/components/Controls/ToggleVideoButton/ToggleVideoButton.tsx:25]: Ok 😞
