### PR TITLE
Disable Join Room button while media permissions are pending

### LINKED ISSUE #201: Video and microphone streams are not added after permissions accept
**Describe the bug**
When a room is already joined, modal video and microphone permissions accept does not add devices streams.

**To Reproduce**
1. Open main page
2. Permission modal will pop up, keep it open
3. Write name, room name and click join room
4. Wait until room will be joined
5. Accept video and microphone permissions on modal

**Expected behavior**
When room is joined, on video and microphone permissions accept it should add these streams.

**Environment:**
 - OS: MacOS Catalina 10.15
 - Browser: Chrome 81.0.4044.138 (Official Build) (64-bit)
 - App Version: 0.1.0
 - SDK Version: 2.4.0
 - Node.js version: 12.12.0

**Additional context**
Name and room name inputs has to be moved to the right to prevent covering by permissions modal

### LINKED ISSUE #220: Invalid video icon state when entering room
**Describe the bug**
When user joins the video room we are seeing that Camera Control Icon does not match whether camera is actually on/off for participant. It shows as "Camera is Off", but the control icon shows that video is enabled. The same appears while using mobile devices.

Another case: 
When I entered chat room first time, camera was off but camera icon was incorrect. Screenshot is attached. It was maybe because Chrome asked to confirm access to camera and mic but after confirmation nothing changed.
In all next cases of opening videochat (all except first) camera is on by default and camera icon is correct.

**To Reproduce**
1. Enter the room created
2. Scroll down to Controls
4. See error video icon show that videocamera is enabled but no stream flows

**Expected behavior**
Camera icon in the controls should show state of camera stream enabled and vice versa.

**Screenshots**
image

**Environment (please complete the following information):**
 - OS: Windows any version, MacOS, iOS 13.5
 - Browser: Chrome > 80, Safari 13.1
 - App Version: master branch of this repository
 - SDK Version: 2.5.0
 - Node.js version: 12.14

### PR DESCRIPTION
**Pull request by timmydoza**
**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### JIRA link(s):

- [AHOYAPPS-707](https://issues.corp.twilio.com/browse/AHOYAPPS-707)

### Description

This PR disabled the Join Room button while the `getUserMedia` promise is pending. I user must allow or deny camera & microphone permissions before they are allowed to join the room.

Resolves #201 
Resolves #220 

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [x] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [x] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

### CODE REVIEW

File: src/components/MenuBar/MenuBar.tsx [hunk 1]
```diff
@@ -124,7 +124,7 @@ export default function MenuBar() {
               type="submit"
               color="primary"
               variant="contained"
-              disabled={isConnecting || !name || !roomName || isFetching}
+              disabled={isAcquiringLocalTracks || isConnecting || !name || !roomName || isFetching}
```
Comment (charliesantos) [inline src/components/MenuBar/MenuBar.tsx:127]: Instead of adding another flag, is it possible to check for the existence of the local track instead?

Comment (timmydoza) [reply src/components/MenuBar/MenuBar.tsx:127]: If the user disables their video, then there would be no video track, but we would still want the user to be able to join the room.  We also want the user to be able to join the room if they deny media permissions.

So this flag indicates whether or not the permissions dialog is still open, not whether or not there are local tracks.
